### ISSUE TITLE
Release tags and changelog

### ISSUE THREAD

**Issue by johnjohndoe** [RobertFischer/Gradle-License-Report#4]
Can you please add **release tags** to your repository whenever a version is published? This should be done in seconds:

```sh
$ git tag -a `v.0.0.1` -m "Short summary."
$ git push origin master --tags
```

Further, it would be very helpful if you could maintain a **changelog**. This can be done either with a seperate file such as [`CHANGELOG.md`](https://github.com/johnjohndoe/TypedPreferences/blob/master/CHANGELOG.md) or with the *GitHub release notes* feature.

**Comment by RobertFischer** [comment]
Sure. Will do moving forward.
